### ISSUE TITLE
bokeh should be an explicit dependency

### ISSUE THREAD

**Issue by fcollonval** [ideonate/bokeh-root-cmd#3]
bokeh was removed from the dependencies in e315b0caa6d43efd976c8d37162fc637e23155c1

But from the code, only `panel` is not lazy loaded. So bokeh should still be a requirement.

https://github.com/ideonate/bokeh-root-cmd/blob/e30566d2a5e4e508ee698853e453bdaedcb7dfe0/bokeh_root_cmd/main.py#L11

**Comment by danlester** [comment]
Frederic! Great to hear from you.

Actually, bokeh and panel have never been an explicit requirement for the published versions of this package: https://github.com/ideonate/bokeh-root-cmd/commits/master/requirements.txt

I understand this is 'wrong' in some sense. My feeling is that you need to be able to install cdsdashboards-singleuser to satisfy a cdsdashboards-compatible JupyterLab environment, but may not want to install all of bokeh, panel, streamlit, voila, r-shiny etc. And it is likely a JupyterLab user trying to make a Bokeh dashboard will understand they need to find the Bokeh package somehow, whereas the bokeh-root-cmd as an addition is a mystery to most end users.

Does that make some sense...?

**Comment by fcollonval** [comment]
Hey Dan,

It can make sense yes. Maybe it would be nice to write that explicitly in the README.
